### PR TITLE
New chapter on github repo - local repo workflow

### PR DESCRIPTION
**Pull request by BioPsykOLD**
I tried to follow @privefl s example on how to add a new chapter, and at the same time incorporate some info on how to do the pull request workflow. I did not know how to verify how my changes actually would translate on the webpage, and perhaps that could be a topic for next chapter?

That said I think the example.Rmd was very nice and easy to follow. Hopefully, the pull request workflow example can be used and further developed by others.

### CODE REVIEW

**Comment by privefl** [comment]
In RStudio, you can use Ctrl+Shift+K to build your page (like any Rmd file) and Ctrl+Shift+B to build the whole book (like a packge).

**Comment by privefl** [comment]
I have added these instructions to https://ipsych-community.github.io/wiki-genetics/index.html#contributing-new-pages.

Please try to build your page.

**Comment by BioPsykOLD** [comment]
Cool! But if I am one of those who does not use Rstudio, do you know an easy way to build the html files from the R console anyways? I checked the bookdown manual and it seems to be ingredients there, but I think it is a little unclear on how to actually get it to work. If you don't know I can try to find out myself, but if you do know I would be happy not having to read through the docs.

**Comment by privefl** [comment]
I've just added the commands to render the pages.

**Comment by BioPsykOLD** [comment]
Can be wise to point out somewhere that this package is needed. 
Error in loadNamespace(name) : there is no package called 'spelling'

**Comment by BioPsykOLD** [comment]
And also note somewhere that it after render can be viewed in browser:
```
firefox docs/index.html
```

**Comment by BioPsykOLD** [comment]
I did git pull to get the latest changes before I built the new html files. Why do think these conflicts appear?

**Comment by privefl** [comment]
- The error about package {spelling} should now be more explicit.

- Don't you think people know how to open HTML files?

- Because of the changes I made to the main repo, you need to get first these changes into your fork, or resolve the conflicts using the GitHub interface (which is simpler).

**Comment by BioPsykOLD** [comment]
1. ok
2. Yes, but when dealing with these knitR things you never really know what to expect the output to be. Sometimes you use a within R command to push to browser, and sometimes like now we can open the index.html to see our changes. Let us see how this develops, we should not have a tutorial on every little keystroke. 
3. Still, I did syns with the original repo. In the merge, the difference I could see was that the html tagging appeared different, which for example could indicate different versions of bookdown. Which version are you using?

**Comment by privefl** [comment]
I use version 0.16, the one from CRAN i believe.

**Comment by BioPsykOLD** [comment]
I used 0.14. So a possibility there was a version miss-match. I'll build using 0.16 next time :)

**Pull request merged**
